#!/usr/bin/env bash
#A script to instll and setup nginx
apt-get -y update
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World!" > /var/www/html/index.html' 
service nginx restart
